// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PersonEntity
    {
        /// <summary>
        /// Initializes a new instance of the PersonEntity class.
        /// </summary>
        public PersonEntity() { }

        /// <summary>
        /// Initializes a new instance of the PersonEntity class.
        /// </summary>
        public PersonEntity(string accountNumber = default(string), int? code = default(int?), int? userId = default(int?), string name = default(string), string surname = default(string), string iDNumber = default(string))
        {
            AccountNumber = accountNumber;
            Code = code;
            UserId = userId;
            Name = name;
            Surname = surname;
            IDNumber = iDNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public int? Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public int? UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IDNumber")]
        public string IDNumber { get; set; }

    }
}
