// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class StatusEntity
    {
        /// <summary>
        /// Initializes a new instance of the StatusEntity class.
        /// </summary>
        public StatusEntity() { }

        /// <summary>
        /// Initializes a new instance of the StatusEntity class.
        /// </summary>
        public StatusEntity(int? statusId = default(int?), string statusTypes = default(string))
        {
            StatusId = statusId;
            StatusTypes = statusTypes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StatusId")]
        public int? StatusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StatusTypes")]
        public string StatusTypes { get; set; }

    }
}
