// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TransactionsEntity
    {
        /// <summary>
        /// Initializes a new instance of the TransactionsEntity class.
        /// </summary>
        public TransactionsEntity() { }

        /// <summary>
        /// Initializes a new instance of the TransactionsEntity class.
        /// </summary>
        public TransactionsEntity(int? code = default(int?), int? accountCode = default(int?), DateTime? transactionDate = default(DateTime?), DateTime? captureDate = default(DateTime?), double? amount = default(double?), string description = default(string))
        {
            Code = code;
            AccountCode = accountCode;
            TransactionDate = transactionDate;
            CaptureDate = captureDate;
            Amount = amount;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int? Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account_code")]
        public int? AccountCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transaction_date")]
        public DateTime? TransactionDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capture_date")]
        public DateTime? CaptureDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
