// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UserEntity
    {
        /// <summary>
        /// Initializes a new instance of the UserEntity class.
        /// </summary>
        public UserEntity() { }

        /// <summary>
        /// Initializes a new instance of the UserEntity class.
        /// </summary>
        public UserEntity(int? userId = default(int?), string userName = default(string), string firstName = default(string), string lastName = default(string), string emailAddress = default(string), DateTime? dateCreated = default(DateTime?), DateTime? lastLogin = default(DateTime?), string password = default(string), string lastUpdatedBy = default(string), int? loginCount = default(int?), bool? forceChangePassword = default(bool?))
        {
            UserId = userId;
            UserName = userName;
            FirstName = firstName;
            LastName = lastName;
            EmailAddress = emailAddress;
            DateCreated = dateCreated;
            LastLogin = lastLogin;
            Password = password;
            LastUpdatedBy = lastUpdatedBy;
            LoginCount = loginCount;
            ForceChangePassword = forceChangePassword;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public int? UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastLogin")]
        public DateTime? LastLogin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastUpdatedBy")]
        public string LastUpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LoginCount")]
        public int? LoginCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ForceChangePassword")]
        public bool? ForceChangePassword { get; set; }

    }
}
